spring.application.name=secondserving

# TODO: For now we will hardcode the properties...but once we containerize and deploy to a VPS we will edit w/ env variables.
# So for now it will be hardcoded with the same values from the dev enviroment

# Postgis

## Database components
db.host=localhost
db.port=5432
db.name=secondserving
db.password=secondserving
db.username=secondserving

## Spring datasource setup
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.name}
spring.datasource.password=${db.password}

# Flyway for version controlling our DB schema...we can disable this for quick prototyping
spring.flyway.enabled=true
# Validate with schema and java classes with hibernate...can set to "create" for quick prototype
spring.jpa.hibernate.ddl-auto=validate