spring.application.name=secondserving

# Postgis

## Database components
db.host=localhost
db.port=5432
db.name=secondserving
db.password=secondserving
db.username=secondserving

## Spring datasource setup
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

# Flyway for version controlling our DB schema...we can disable this for quick prototyping
spring.flyway.enabled=true
# Validate with schema and java classes with hibernate...can set to "create" for quick prototype
spring.jpa.hibernate.ddl-auto=validate

# JWT security stuff stuff
app.jwt.secret=Zm9yLXRlc3RzLW9ubHktdXNlLWEtbG9uZy1yYW5kb20tYmFzZTY0LXNlY3JldC12YWx1ZS1oZXJl
app.jwt.expiration-ms=3600000
app.jwt.cookie-name=access_token
app.jwt.cookie-secure=false
app.jwt.cookie-same-site=Lax
